### PR TITLE
md5 -> sha256, added @sigmavirus24 as a maintainer

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Argh! Forgot to tick build number. Fixed.

**Comment by sigmavirus24** [comment]
This looks fine to me. :)

**Comment by jakirkham** [comment]
So, it isn't a big deal to change the build number for metadata changes (e.g. added maintainers). We were initially very interested in bumping the build number everytime there was a change. Now this mostly happens if there is a notable change in the build process. Ultimately there is no strict rule about this. I'm happy to defer to your judgement on your feedstock. 😄

**Comment by pmlandwehr** [comment]
Eh - just trying to follow form. I can leave the build number un-bumped.

**Comment by jakirkham** [comment]
Honestly, one could argue the checksum change is worthy of a build number bump. People have argued that metadata changes deserve a build number bump. As stated, there is no rule and I'm happy to let you do what you want. Just letting you know how common thought has evolved on this point.

**Pull request merged**
