### PR TITLE
Fix brotli dep

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@ocefpaf, this was changed in https://github.com/conda-forge/urllib3-feedstock/pull/65, but `brotli` is not a python package.

**Comment by sethmlarson** [comment]
I'm not sure this is correct. [This feedstock](https://github.com/conda-forge/brotli-feedstock) is the package we want to target to get the binary bindings for libbrotli, should we use `brotli-split` instead?

**Comment by isuruf** [comment]
Brotli-split is not a package. It is just a name used in the recipe. What you want is brotli-python from that feedstock

**Review by ocefpaf — APPROVED** [review]

**Review by sethmlarson — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
